- request:
    method: POST
    url: ^/auth/otp/send-otp-code$
  response:
    - status: 200
      latency: 1000
      file: api/POST_200_otp.json

- request:
    method: POST
    url: ^/auth/otp/verify-code$
  response:
    - status: 200
      latency: 1000
      file: api/POST_200_otp.json

- request:
    method: GET
    url: ^/miscelanium/countries$
  response:
    - status: 200
      latency: 5000
      file: api/GET_200_countries.json
