import type { Metadata } from 'next';

import { avenirLt, bigCaslo } from '@/config/fonts';
import './globals.css';
import "../../node_modules/flag-icons/css/flag-icons.min.css";

export const metadata: Metadata = {
  title: "Wynn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bigCaslo.className} ${avenirLt.className}`}
      >
        {children}
        <div id="tooltip-root"></div>
      </body>
    </html>
  );
}
